---
title: "Assignment 1"
author: "Sajag Swami"
date: "Feb 10, 2021"
output:
    BiocStyle::html_document
editor_options:
    chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning= FALSE, size = 'tiny')
```

### Importing necessary libraries
```{r}
library(ggplot2)
library(GGally)
```


## 1

a.
```{r}
a <- 1:8
b <- rev(1:7)
ab <- c(a, b)
```

b. 
```{r}
arr <- vector()
k <- 0
for (i in 1:5){
  for (j in 1:i){
    arr[k] <- i
    k <- k + 1
  }
}
```

c. 
```{r}
m1 <- matrix(rep(rep(1, 3), 3), nrow = 3, ncol =3)
m2 <- diag(1, 3)
m3 <- m1 - m2
```

## 2
```{r}
func_y <- function(x){
  if(x <= 0){
    y = -1*x ^ 3
  }
  else if(x > 0 & x <= 1){
    y <- x^2
  }
  else if(x > 1){
    y <- x^0.5
  }
  return(y)
}

x_vals <- as.numeric(seq(-2, 2, length.out=1000))
y_vals <- as.numeric(lapply(x_vals, func_y))
df <- data.frame(x_vals, y_vals)
ggplot(data = df, aes(x=x_vals, y=y_vals), xlab="x", ylab="f(x)") + geom_point()
```

## 3
Done on paper

## 4

a. Done

b.
```{r}
data_analysis  <- readRDS(file.path(getwd(), "Data", "data_analysis.rds"))
```

```{r}
df <- as.data.frame(data_analysis)
```

c.
```{r}
participants <- nrow(df)
```

d.
```{r}
variables <- ncol(df)
```

e.
```{r}
names(df)
ggpairs(df, c("Age", "BMI", "Gender", "TLAC_1", "MVPA"), 
        diag = list(continuous ="barDiag", discrete = "barDiag", na = "naDiag") )
```

f.
```{r}
p1 <- ggplot(df, aes(x=MVPA, group=Gender, fill = Gender)) + 
  geom_histogram(aes(y=..density..), 
                 position="identity", bins = 20, alpha = 0.6) +
  theme_bw()+
  scale_fill_manual(values=c("black", "gray"), 
                       name="")+
  labs(x='MVPA', y='Proportion') 
plot(p1)
```

g.
```{r}
p2 <- ggplot(df, aes(x=MVPA, group=BMI_cat, fill = BMI_cat)) + 
  geom_histogram(aes(y=..density..), 
                 position="identity", bins = 20, alpha = 0.3) +
  theme_bw()+
  scale_fill_manual(values=c("green", "pink", "blue", "red"), 
                       name="")+
  labs(x='MVPA', y='Proportion')
plot(p2)
```

h.
Males seem to have more MVPA than females (distribution is more skewed towards the right).

i.
```{r}
p3 <- ggplot(df, aes(x=Age, y=MVPA)) + geom_point(color ='blue', alpha=0.5) + theme_dark()+ theme(axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16))
plot(p3)
```

j.
```{r}
lm.fit <- lm(df$MVPA ~ df$Age)
p3 <- p3+  geom_abline(intercept = coefficients(lm.fit)[1], slope = coefficients(lm.fit)[2],
              colour = "red", size = 1, linetype = "solid") + theme(axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16))
plot(p3)
print(summary(lm.fit)$r.squared)
print(cor(df$MVPA, df$Age))
```

l.
Homoscedasticity is not present 








